Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -8,7 +8,8 @@
 GITHUB_RAW="https://raw.githubusercontent.com/tokektv/nodogsplash/refs/heads/main/"
 SPLASH_URL="$GITHUB_RAW/splash.html"
 CONFIG_URL="$GITHUB_RAW/nodogsplash"
-MACLIST_URL="$GITHUB_RAW/allowed_macs.txt"
+MACLIST_URL="$GITHUB_RAW/maclist.txt"
+INIT.D_URL="$GITHUB_RAW/init.d/nodogsplash"
 FALLBACK_MODE=0
 
 echo "[1] UPDATE DAN INSTALASI PAKET"
@@ -30,6 +31,13 @@ download_file() {
   echo "❌ Gagal mengunduh"
   return 1
 }
+
+# Download file init.d
+wget -O /etc/init.d/nodogsplash "$INIT.D_URL" || {
+     echo "Error: Gagal download" >&2
+     exit 1
+   }
+chmod +x /etc/init.d/nodogsplash
 
 # Download splash.html
 if ! download_file "$SPLASH_URL" "/etc/nodogsplash/htdocs/splash.html"; then
@@ -70,12 +78,12 @@ EOL
   FALLBACK_MODE=1
 fi
 
-# Download MAC Whitelist
-mkdir -p /etc/init.d/
-if ! download_file "$MACLIST_URL" "/etc/nodogsplash/allowed_macs.txt"; then
-  cat > /etc/nodogsplash/allowed_macs.txt << 'EOL'
-AA:BB:CC:DD:EE:FF  # Device Admin
-11:22:33:44:55:66  # Printer
+# Download TRUSHTED MAC
+mkdir -p /etc/nodogsplash
+if ! download_file "$MACLIST_URL" "/etc/nodogsplash/trusted_macs.txt"; then
+  cat > /etc/nodogsplash/trusted_macs.txt << 'EOL'
+AA:BB:CC:DD:EE:FF
+11:22:33:44:55:66
 EOL
   FALLBACK_MODE=1
 fi
@@ -93,36 +101,19 @@ uci add firewall rule
 uci set firewall.@rule[-1].name='MANAGEMENT-WAN'
 uci set firewall.@rule[-1].src='wan'
 uci set firewall.@rule[-1].proto='tcp'
-uci set firewall.@rule[-1].dest_port='22 80 443'
+uci set firewall.@rule[-1].dest_port='21 22 80 443'
 uci set firewall.@rule[-1].target='ACCEPT'
 
 uci add firewall rule
 uci set firewall.@rule[-1].name='MANAGEMENT-WWAN'
 uci set firewall.@rule[-1].src='wwan'
 uci set firewall.@rule[-1].proto='tcp'
-uci set firewall.@rule[-1].dest_port='22 80 443'
+uci set firewall.@rule[-1].dest_port='21 22 80 443'
 uci set firewall.@rule[-1].target='ACCEPT'
 
-echo "[4] SETUP AUTO-UPDATE MAC LIST"
-# Buat script update terpisah
-cat > /etc/nodogsplash/update_maclist.sh << 'EOL'
-#!/bin/sh
-MACLIST_URL="https://raw.githubusercontent.com/tokektv/nodogsplash/refs/heads/main/allowed_macs.txt"
-TEMP_FILE="/tmp/maclist.tmp"
-
-if wget -q -O "$TEMP_FILE" "$MACLIST_URL" && grep -qE '([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}' "$TEMP_FILE"; then
-    mv "$TEMP_FILE" "/etc/nodogsplash/allowed_macs.txt"
-    /etc/init.d/nodogsplash restart
-    echo "$(date) - MAC list updated" >> /var/log/maclist_update.log
-else
-    echo "$(date) - Update failed" >> /var/log/maclist_update.log
-fi
-EOL
-
-chmod +x /etc/nodogsplash/update_maclist.sh
-
 # Jadwalkan update tiap 6 jam
-(crontab -l 2>/dev/null; echo "0 */6 * * * /etc/nodogsplash/update_maclist.sh") | crontab -
+(crontab -l 2>/dev/null; echo "0 */6 * * * wget -O /etc/nodogsplash/trusted_macs.txt https://raw.githubusercontent.com/tokektv/nodogsplash/refs/heads/main/maclist.txt
+") | crontab -
 
 echo "[5] RESTART SERVICE"
 /etc/init.d/firewall restart
@@ -138,14 +129,14 @@ Fitur yang aktif:
 1. NoDogSplash dengan:
    - splash.html: $(if [ $FALLBACK_MODE -eq 0 ]; then echo "GitHub"; else echo "Lokal"; fi)
    - config: $(if [ $FALLBACK_MODE -eq 0 ]; then echo "GitHub"; else echo "Lokal"; fi)
-2. MAC Whitelist:
+2. MAC TRUSHTED MAC:
    - Sumber: $(if [ $FALLBACK_MODE -eq 0 ]; then echo "GitHub"; else echo "Lokal"; fi)
    - Auto-update tiap 6 jam
 3. Firewall:
    - Port 22,80,443 terbuka untuk WAN/WWAN
 
 Daftar MAC yang diizinkan:
-$(cat /etc/nodogsplash/allowed_macs.txt)
+$(cat /etc/nodogsplash/trusted_macs.txt)
 
 Akses hotspot:
 - http://$(uci get network.lan.ipaddr):2050
